id: PA6AF7A3F
initial_creation_type: ocr
source_metadata:
  volumes:
    5a61266490eb425abe24ce659ae0bee4:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པའི་གཟུངས་བཀླག་པའི་ཆོ་ག་མདོ་སྡེ་ལས་བཏུས་པ།
      total_pages: 1044
      volume_number: 38
